#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GetSanger.Droid.Resource", IsApplication=true)]

namespace GetSanger.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F02000D
			public const int accountIcon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int activityIcon = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int appleIcon = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int ascendingSort = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int categoryIcon = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int chatIcon = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int emailIcon = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int facebookIcon = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int getSangerIcon = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int getSangerIconHD = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int getSangerIconTransparent = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int googleIcon = 2130837528;
			
			// aapt resource value: 0x7F020000
			public const int IconArrangement = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int IconBeauty = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int IconCleaning = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int IconComputersAndSmartphones = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int IconDelivery = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int IconElectrician = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int IconGardening = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int IconHandiman = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int IconHouseDevices = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int IconPets = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int IconStudies = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int IconVehicles = 2130837515;
			
			// aapt resource value: 0x7F020019
			public const int ic_scrolldown = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int jobOfferIcon = 2130837530;
			
			// aapt resource value: 0x7F02000C
			public const int LocationIcon = 2130837516;
			
			// aapt resource value: 0x7F02001B
			public const int notificationPic = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int phone = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int profile = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int ratingStarOff = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int ratingStarOff2x = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int ratingStarOn = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int ratingStarOn2x = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int rolling = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int whatsapp = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int getSangerIcon = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int com_google_firebase_crashlytics_mapping_file_id = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int MainTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
